# Generated by Django 5.0 on 2024-01-06 21:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buy', '0001_initial'),
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buy',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer'),
        ),
    ]
