# Generated by Django 5.0 on 2023-12-27 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='subscription',
            table='subscription',
        ),
    ]
