# Generated by Django 5.0 on 2024-01-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0002_alter_subscription_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='planes',
            field=models.FloatField(choices=[('basic', 10), ('gold', 20), ('platinum', 30)], max_length=20, null=True),
        ),
    ]
