# Generated by Django 5.0 on 2024-01-21 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0004_alter_subscription_planes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='planes',
            field=models.CharField(choices=[('basic', 'basic'), ('gold', 'gold'), ('platinum', 'platinum')], max_length=10, null=True),
        ),
    ]
