# Generated by Django 5.0 on 2024-01-21 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0005_alter_subscription_planes'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='basic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='platinum',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subscription',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
