# Generated by Django 5.0 on 2024-01-21 04:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0006_subscription_basic_subscription_platinum_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='description',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='planes',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='title',
        ),
    ]
