# Generated by Django 5.0 on 2024-01-21 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0007_remove_subscription_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='basic',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='platinum',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='premium',
        ),
        migrations.AddField(
            model_name='subscription',
            name='precio',
            field=models.CharField(blank=True, choices=[('10', 'Basic'), ('20', 'Gold'), ('30', 'Platinum')], max_length=50),
        ),
    ]
