# Generated by Django 5.0 on 2023-12-18 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_del_titular', models.CharField(max_length=200)),
                ('numero_de_tarjeta', models.FloatField()),
                ('fecha_de_caducidad', models.DateField()),
                ('cvv', models.CharField(max_length=4)),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
