# Generated by Django 5.0 on 2024-01-13 20:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
        ('information', '0006_remove_paises_argentina_remove_paises_bolivia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='information',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='information.information'),
        ),
    ]
