# Generated by Django 5.0.1 on 2024-01-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_buyer_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='information',
        ),
        migrations.RemoveField(
            model_name='buyer',
            name='user',
        ),
    ]
