# Generated by Django 5.0.1 on 2024-01-27 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_remove_buyer_information_remove_buyer_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='payment_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
