# Generated by Django 5.0.1 on 2024-01-28 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_remove_buyer_information'),
        ('information', '0019_remove_information_buyer'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='information',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='information.information'),
        ),
    ]
