# Generated by Django 5.0 on 2024-01-09 02:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_remove_information_apellido_remove_information_email_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='tipo_documento',
            field=models.CharField(blank=True, choices=[('DNI', 'Documento Nacional de Identidad'), ('PAS', 'Pasaporte'), ('CAR', 'Carnet de extranjeria')], max_length=50),
        ),
        migrations.AlterField(
            model_name='information',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
