# Generated by Django 5.0 on 2024-01-09 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0003_alter_information_tipo_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='information',
            name='telefono',
            field=models.CharField(blank=True, max_length=10, unique=True),
        ),
    ]
