# Generated by Django 5.0 on 2024-01-13 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0005_paises_alter_information_pais'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paises',
            name='argentina',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='bolivia',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='brasil',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='chile',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='colombia',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='ecuador',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='mexico',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='paraguay',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='peru',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='uruguay',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='venezuela',
        ),
        migrations.AddField(
            model_name='paises',
            name='pais',
            field=models.CharField(choices=[('PE', 'Perú'), ('VE', 'Venezuela'), ('MX', 'México'), ('EC', 'Ecuador'), ('AR', 'Argentina'), ('UY', 'Uruguay'), ('CL', 'Chile'), ('BO', 'Bolivia'), ('PY', 'Paraguay'), ('BR', 'Brasil'), ('CO', 'Colombia')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='information',
            name='pais',
            field=models.CharField(choices=[('PE', 'Perú'), ('VE', 'Venezuela'), ('MX', 'México'), ('EC', 'Ecuador'), ('AR', 'Argentina'), ('UY', 'Uruguay'), ('CL', 'Chile'), ('BO', 'Bolivia'), ('PY', 'Paraguay'), ('BR', 'Brasil'), ('CO', 'Colombia')], default='PE', max_length=2, null=True),
        ),
    ]
