# Generated by Django 5.0 on 2024-01-13 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0006_remove_paises_argentina_remove_paises_bolivia_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='paises',
            table='country',
        ),
    ]
