# Generated by Django 5.0 on 2024-01-14 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0007_alter_paises_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('autos', models.CharField(choices=[('SEDAN', 'Sedán'), ('HATCHBACK', 'Hatchback'), ('COUPE', 'Coupé'), ('STATION_WAGON', 'Station wagon'), ('SUV', 'Suv'), ('CROSSOVER', 'Crossover'), ('CONVERTIBLE', 'Convertible'), ('4X4', '4x4'), ('OTROS', 'Otros')], max_length=30, null=True)),
            ],
            options={
                'db_table': 'autos',
            },
        ),
        migrations.RemoveField(
            model_name='information',
            name='direccion',
        ),
        migrations.AlterField(
            model_name='information',
            name='tipo_vehiculo',
            field=models.CharField(choices=[('SEDAN', 'Sedán'), ('HATCHBACK', 'Hatchback'), ('COUPE', 'Coupé'), ('STATION_WAGON', 'Station wagon'), ('SUV', 'Suv'), ('CROSSOVER', 'Crossover'), ('CONVERTIBLE', 'Convertible'), ('4X4', '4x4'), ('OTROS', 'Otros')], default='SEDAN', max_length=30, null=True),
        ),
    ]
