# Generated by Django 5.0 on 2024-01-22 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0009_information_subscription'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='user',
        ),
        migrations.AddField(
            model_name='information',
            name='apellidos',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='information',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='information',
            name='nombre',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
