# Generated by Django 5.0.1 on 2024-01-23 01:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0010_remove_information_user_information_apellidos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='subscription',
        ),
    ]
