# Generated by Django 5.0.1 on 2024-01-28 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_remove_buyer_information'),
        ('information', '0017_alter_information_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='information',
            name='buyer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer'),
        ),
    ]
