# Generated by Django 5.0.1 on 2024-01-28 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0018_information_buyer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='information',
            name='buyer',
        ),
    ]
